image:
  name: node:14.19
pipelines:
  custom:
    dont_run:
      - step: &install_build_test
          name: install
          caches:
            - node
          script:
            - npm ci
            - npm run lint:check
            - npm run build
            - npm test
          artifacts:
            - dist/**
      - step: &publish
          name: publish
          caches:
            - node
          script:
            - npm publish
  branches:
    master:
      - step: *install_build_test
      - step: *publish
  pull-requests:
    "**":
      - step: *install_build_test
